const data = {
  products: [
    {
      name: 'Power bank',
      slug: 'Power bank',
      category: 'Power',
      image: '/images/powerbank.jpg',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'New Age Power bank',
    },
    {
      name: 'Type C HDMI',
      slug: 'HDMI',
      category: 'HDMI',
      image: '/images/2.webp',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'Hdmi',
    },
    {
      name: 'Charger',
      slug: 'chaarger',
      category: 'Power',
      image: '/images/1.jpg',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'orignal charger',
    },
    {
      name: 'Type C USB',
      slug: 'USB',
      category: 'Power',
      image: '/images/3.webp',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'orignal USB',
    },
    {
      name: 'Type C USB',
      slug: 'USB',
      category: 'Power',
      image: '/images/4.jpg',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'orignal USB',
    },
    {
      name: 'Type C Charger',
      slug: 'Charger',
      category: 'Power',
      image: '/images/5.webp',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'orignal Charger',
    },
    {
      name: 'Bluetooth Speaker',
      slug: 'soeaker',
      category: 'sound',
      image: '/images/6.webp',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'smooth bluetooth speaker',
    },
    {
      name: 'Bluetooth Speaker',
      slug: 'soeaker',
      category: 'sound',
      image: '/images/7.jpg',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'smooth bluetooth speaker',
    },
    {
      name: 'rok Bluetooth earpiece',
      slug: 'earpiece',
      category: 'sound',
      image: '/images/8.webp',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'bluetooth earpiece',
    },
    {
      name: 'rok Bluetooth headset',
      slug: 'headset',
      category: 'sound',
      image: '/images/12.png',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'bluetooth headset',
    },
    {
      name: 'rok Bluetooth earpiece',
      slug: 'earpiece',
      category: 'sound',
      image: '/images/9.webp',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'bluetooth earpiece',
    },
    {
      name: 'rok Bluetooth earbuds',
      slug: 'earbuds',
      category: 'sound',
      image: '/images/10.webp',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'bluetooth earbuds',
    },
    {
      name: 'Bluetooth keyboard and mouse',
      slug: 'Keyboard and mouse',
      category: 'Accessories',
      image: '/images/11.jpg',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'Keyboard and mouse',
    },
    {
      name: 'wireless charger',
      slug: 'wireless charger',
      category: 'Accessories',
      image: '/images/13.jpg',
      price: 15000,
      brand: 'New Age',
      rating: 4.5,
      numReviews: 8,
      countInStock: 50,
      description: 'wireless charger',
    },
  ],
};
export default data;
